// Generated by CoffeeScript 1.6.3
(function() {
  var c, cb, folder, fs, http, path, port, svc, url;

  fs = require('fs');

  path = require('path');

  http = require('http');

  url = require('url');

  folder = process.argv[2] || "C:\\node\\filemonitor\\test";

  port = process.argv[3] || 8080;

  c = [];

  cb = function() {
    c = [];
    return require('file').walk(folder, function(x, dirPath, dirs, names) {
      return names.forEach(function(file) {
        return fs.stat(file, function(err, stat) {
          var o;
          o = {
            file: file,
            path: path.relative(folder, file),
            mtime: stat.mtime
          };
          return c.push(o);
        });
      });
    });
  };

  setInterval(cb, 5000);

  svc = http.createServer(function(req, res) {
    var p, t, x;
    p = url.parse(req.url, true);
    t = p.query.term;
    x = c;
    if (t) {
      x = x.filter(function(e) {
        return e.file.indexOf(t) >= 0;
      });
    }
    return res.end(JSON.stringify(x));
  });

  svc.listen(port);

}).call(this);
