// Generated by CoffeeScript 1.6.3
(function() {
  var c, cb, folder, fs, http, path, port, svc;

  fs = require('fs');

  path = require('path');

  http = require('http');

  folder = process.argv[2] || "C:\\node\\filemonitor\\test";

  port = process.argv[3] || 8080;

  c = [];

  cb = function() {
    c = [];
    return require('file').walk(folder, function(x, dirPath, dirs, names) {
      return names.forEach(function(file) {
        return fs.stat(file, function(err, stat) {
          var o;
          o = {
            path: path.relative(folder, file),
            mtime: stat.mtime
          };
          return c.push(o);
        });
      });
    });
  };

  setInterval(cb, 5000);

  svc = http.createServer(function(req, res) {
    return res.end(JSON.stringify(c));
  });

  svc.listen(port);

  /*
  	for dir in dirs
  		do (dir) ->
  			fs.readdir dir, (err, files) ->
  				console.log 'ok'
  				files.forEach (file) ->
  					fs.stat file, (err, stat) ->
  						console.log file if stat.isDirectory?				
  fs.stat folder, (err, stats) -> 
  	throw err if (err)
  	console.log 'stats: ' + JSON.stringify(stats)
  */


}).call(this);
